project:
  swagger:
    enabled: true
    basePackages:
      - cn.zhumingwu
    api-info:
      title: swagger api
      description: 优雅的restful风格
      terms-of-service-url: http://terms.zhumingwu.cn
      version: 1.0
      contact:
        name: zhumingwu
        url: https://www.zhumingwu.cn
        email: admin@zhumingwu.cn

  consul:
    enabled: true
    minutes: 1
    host: 10.168.4.14
    port: 8500
    health:
      enabled: true
logging:
  level:
    web: debug
    cn.zhumingwu: debug