server:
  port: 8080

spring:
  application:
    name: rest-data
  cloud:
    config:
      uri: http://localhost:8500 
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.168.4.22:5321/mti_test?currentSchema=public
    username: postgres
    password: postgres
  daoshu:
    tables:
      prefix-matches:
      - s*_
      - t*_
      - us*_
    changes:
      append:
      - t_: {prefix: 'test_', suffix: '_result'} #以t_开头的表，前增test_，后增_result
      - s_: {suffix: '_test'} #以s开头的表，后增_test
      - us_: {prefix: 'user_'} #以us_开头的表，前增user_
      remove:
      - _ #移除 _
      replace: {land: 'plan', jiefang: 'liberate'}

context: 
  listener: 
    classes: ltd.fdsa.fdsql.web.ApplicationEventListener


management:
  endpoints:
    web:
      exposure:
        include: "zhumingwu,prometheus,health"
  endpoint:
    health:
      show-details: always 
