spring:
  freemarker:
    #template-loader-path: classpath:/templates/
    template-loader-path: file:/Work/java/fast-data/fast-data-switch/fast-data-switch-admin/src/main/resources/templates
    charset: UTF-8
    suffix: .ftl
    request-context-attribute: request
    expose-request-attributes: true
    settings:
      number_format: 0.##
      template_update_delay: 0

  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  application:
    name: gateway


  profiles:
    active: dev
  redis.hostName: 115.28.92.178
  redis.port: 6379
  redis.password: xxx
  redis.pool.maxActive: 8
  redis.pool.maxWait: -1
  redis.pool.maxIdle: 8
  redis.pool.minIdle: 0
  redis.timeout: 0
  jpa:
    database-platform: org.hibernate.dialect.SQLiteDialect
    generate-ddl: true
    show-sql: false

  datasource:
    master:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.sqlite.JDBC
      url: ${database.master.url}
      username: ${database.master.username}
      password: ${database.master.password}
      maxActive: 20
      maxWait: 10000
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      filters: stat,slf4j
      timeBetweenLogStatsMillis: 5000
      druid:
        maxWait: 60000
        filter:
          stat:
            enabled: true
  cloud:
    consul:
      host: 10.168.4.14
      port: 8500
      discovery:
        prefer-ip-address: true
        register: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

  mail.host: smtp.qq.com
  mail.port: 25
  mail.username: xxx@qq.com
  mail.password: xxx
  mail.properties.mail.smtp.auth: true
  mail.properties.mail.smtp.starttls.enable: true
  mail.properties.mail.smtp.starttls.required: true
  mail.properties.mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
### , access token
project.job.accessToken: 
### , i18n (default empty as chinese, "en" as english)
project.job.i18n:
