server:
  port: 8096
spring:
  application:
    name: system-search
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.168.4.172:5321/dev?currentSchema=public
    username: postgres
    password: postgres
  data:
    neo4j:
      uri: bolt://neo4j:7687
      username: neo4j
      password: qwe123!@#
project:
  swagger:
    enabled: true
    basePackages:
      - ltd.fdsa
    info:
      version: 1.0
      title: "test Document"
      description: "test Document"
      contact:
        name: zhumingwu
        email: zhumingwu@126.com
        url: https://github.com/fdsa
  consul:
    enabled: true
    host: 10.168.4.14
    port: 8500
    health:
      enabled: true
logging:
  level:
    web: debug
    ltd.fdsa: debug