jdbc:
  config:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://10.168.4.172:5321/shanghai
    userName: postgres
    password: postgres
    parantName: ltd.fdsa
    schemaName: shanghai
    packageName: test
    dbType: POSTGRE_SQL
    table:
    - s_user
    - s_role
    tablePrefix:
      - s_
      - t_
      - bo_
      - r_