server:
  port: 8080
spring:
  application:
    name: client
  profiles:
    active: dev
  jpa:
    open-in-view: false
  devtools:
    add-properties: true
  datasource:
    master:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: ${database.master.driver}
      url: ${database.master.url}
      username: ${database.master.username}
      password: ${database.master.password}
      maxActive: 20
      maxWait: 10000
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      timeBetweenLogStatsMillis: 5000
      druid:
        maxWait: 60000
        filter:
          stat:
            enabled: true
    slaves:
      - type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: ${database.master.driver}
        url: ${database.slave1.url}
        username: ${database.slave1.username}
        password: ${database.slave1.password}
      - type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: ${database.master.driver}
        url: ${database.slave2.url}
        username: ${database.slave2.username}
        password: ${database.slave2.password}
management:
  endpoints:
    web:
      exposure:
        include: "info,health,prometheus,druid"
  endpoint:
    health:
      show-details: always
project:
  rpc:
    enabled: true
    packages: ltd.fdsa.api.service
  swagger:
    enabled: true
    basePackages:
      - ltd.fdsa
    api-info:
      title: swagger api
      description: 优雅的restful风格
      terms-of-service-url: http://fdsa.ltd
      version: 1.0
      contact:
        name: zhumingwu
        url: http://fdsa.ltd
        email: zhumingwu@fdsa.ltd
  consul:
    enabled: true
    minutes: 1
    host: 10.168.4.14
    port: 8500
    health:
      enabled: true
  rest-api:
    enabled: true
    catalog:
    schema: public
    tables:
      "[bm_*]":
        removes:
          - prefix: bm_
            suffix: _event
        appends:
          - prefix: entity_
            suffix: controller
        replaces:
          - key1: value1
          - key2: value2
        column:
          removes:
            - prefix:
              suffix:
          appends:
            - prefix:
              suffix:
          replaces:
            - key1: value1
            - key2: value2
    acl:
      "[bm_*]":
        - CREATE
        - UPDATE
        - QUERY_LIST
        - DELETE

logging:
  path: /var/log/${spring.application.name}-${server.port}
  level:
    web: INFO
    ltd.fdsa: DEBUG
  pattern:
    console: '[%highlight(%-4level)] %msg%n'
