database:
  master:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5321/dev_database?currentSchema=public
    username: postgres
    password: postgres
  slave1:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5321/dev_database?currentSchema=public
    username: postgres
    password: postgres
  slave2:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5321/dev_database?currentSchema=public
    username: postgres
    password: postgres 
    
logging:
  path: /var/log/${spring.application.name}-${server.port}
  level:
    ltd.fdsa: DEBUG
#  pattern:
#    console: '[%highlight(%-4level)] %msg%n'
 
