database:
  master:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.dev:3306/dev?useSSL=false&characterEncoding=utf-8&serverTimezone=GMT
    username: mysql
    password: MySQL123$
  slave1:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.dev:3306/dev?useSSL=false&characterEncoding=utf-8&serverTimezone=GMT
    username: mysql
    password: MySQL123$
  slave2:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.dev:3306/dev?useSSL=false&characterEncoding=utf-8&serverTimezone=GMT
    username: mysql
    password: MySQL123$

logging:
  path: /var/log/${spring.application.name}-${server.port}
  level:
    ltd.fdsa: DEBUG
  pattern:
    console: '[%highlight(%-4level)] [%20.20logger] %msg%n'
