server:
  port: 8099

spring:
  devtools:
    add-properties: false
  application:
    name: demo
  profiles:
    active: dev
  cloud:
    consul:
      host: 10.168.4.14
      port: 8500
      discovery:
        prefer-ip-address: true
        register: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver #com.mysql.jdbc.Driver
    url: jdbc:postgresql://10.168.4.172:5321/shanghai?currentSchema=shanghai
    username: postgres
    password: postgres
    slaves:
      - type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.postgresql.Driver #com.mysql.jdbc.Driver
        url: jdbc:postgresql://10.168.4.172:5321/songjiang?currentSchema=public
        username: postgres
        password: postgres
      - type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.postgresql.Driver #com.mysql.jdbc.Driver
        url: jdbc:postgresql://10.168.4.172:5321/risk-insight?currentSchema=public
        username: postgres
        password: postgres
      - type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.postgresql.Driver #com.mysql.jdbc.Driver
        url: jdbc:postgresql://10.168.4.172:5321/risk-insight2?currentSchema=public
        username: postgres
        password: postgres
      - type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.postgresql.Driver #com.mysql.jdbc.Driver
        url: jdbc:postgresql://10.168.4.172:5321/shanghai?currentSchema=shanghai
        username: postgres
        password: postgres
    
logging: 
  level:
    web: DEBUG



    
